{
 "title": "Joycon Dashboard",
 "time": { "from": "2026-09-01T15:46:33.110Z", "to": "2026-09-01T15:47:45.794Z" },
 "panels": [
  {
   "title": "Maximum Dynamic Linear Acceleration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "ingested_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "la", "id": "3", "type": "max" }
     ],
     "timeField": "ingested_at"
    }
   ]
  },
  {
   "title": "Maximum Rotational Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "ingested_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rs", "id": "3", "type": "max" }
     ],
     "timeField": "ingested_at"
    }
   ]
  },
  {
   "title": "Song playing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "3", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "ingested_at"
    }
   ]
  },
  {
   "title": "Raw Accelerometer Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "ingested_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "ax", "id": "3", "type": "avg" },
      { "field": "ay", "id": "4", "type": "avg" },
      { "field": "az", "id": "5", "type": "avg" }
     ],
     "timeField": "ingested_at"
    }
   ]
  },
  {
   "title": "Raw Gyroscope Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "ingested_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "gx", "id": "1", "type": "avg" },
      { "field": "gy", "id": "3", "type": "avg" },
      { "field": "gz", "id": "4", "type": "avg" }
     ],
     "timeField": "ingested_at"
    }
   ]
  },
  {
   "title": "Total Power ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "ingested_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "tp", "id": "1", "type": "avg" }
     ],
     "timeField": "ingested_at"
    }
   ]
  },
  {
   "title": "Tabular Format of Joycon Data",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "ingested_at"
    }
   ]
  }
 ]
}